language: python
python:
    - 2.7
    - 3.4

install:
    # install-requires dependencies
    - pip install nose
    - pip install pylint
    - pip install --user --editable .

script:
    - nosetests
    - pylint --disable=C,R,W,E1101,E0611 --reports=no {{ cookiecutter.project_name }}
